## Import Packages

In [ ]:
import pandas as pd
from os.path import join

## Functions

### Simple Function

In [ ]:
def add_numbers(a: float, b: float) -> float:
    """
    Add two numeric values and return their sum.

    This function takes two numbers, adds them together, and returns the result.
    Although the parameters are annotated as floats, integers can also be passed
    because they are compatible with numeric addition in Python.

    Parameters
    ----------
    a : float
        The first number to add.
    b : float
        The second number to add.

    Returns
    -------
    float
        The sum of `a` and `b`.

    Examples
    --------
    >>> add_numbers(10.5, 4.5)
    15.0

    >>> add_numbers(2, 3)
    5
    """

    c = a + b
   
    return c

In [ ]:

URL = "https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/"

join(URL,'public_schema','customers.csv')

'https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/customers.csv'

### CSV Dowloader 1

In [ ]:
csv_files = ['customers', 'orders']

def csv_dowloader(csv_files:list, source:str, destination: str,):
    for i in csv_files:
        print(f"trying to read: {i}")
        print(f"source: {source}")
        print(f"destination: {destination}")

        df = pd.read_csv(f"{join(source,i)}.csv")
        print(f"{i} shape: {df.shape}")
        df.to_csv(join(destination,f"{i}.csv"))
        print(10*"=")
    
    return 'Okay'

In [24]:
URL = "https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema"
# DESTINATION = '/Users/karen/Desktop/aca/lab/sql_module/data/public_schema'
DESTINATION = '../data/public'
csv_dowloader(csv_files= csv_files,source=URL,destination=DESTINATION)

trying to read: customers
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema
destination: ../data/public
customers shape: (2000, 5)
==========
trying to read: orders
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema
destination: ../data/public
orders shape: (200, 5)
==========

'Okay'

### CSV Dowloader 2

In [29]:
def csv_dowloader(csv_files:list, source:str, destination: str, type:str = 'csv'):
    for i in csv_files:
        print(f"trying to read: {i}")
        print(f"source: {source}")
        print(f"destination: {destination}")

        df = pd.read_csv(f"{join(source,i)}.csv")
        print(f"{i} shape: {df.shape}")
        
        file_name = join(destination,f"{i}.{type}")
        print(file_name)
        if type == 'xlsx':
            df.to_excel(file_name,index= False)
        elif type == 'parquet':
            df.to_parquet(file_name, index= False)
        else:
            df.to_csv(file_name,index= False)
        print(10*"=")
    
    return 'Okay'

In [30]:
URL = "https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema"
# DESTINATION = '/Users/karen/Desktop/aca/lab/sql_module/data/public_schema'
DESTINATION = '../data/public'
csv_dowloader(csv_files= csv_files,source=URL,destination=DESTINATION,type='xlsx')

trying to read: customers
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema
destination: ../data/public
customers shape: (2000, 5)
../data/public/customers.xlsx
==========
trying to read: orders
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema
destination: ../data/public
orders shape: (200, 5)
../data/public/orders.xlsx
==========

'Okay'

### CSV Dowloader Improt

In [1]:
from utils import csv_dowloader

In [ ]:
csv_dowloader

In [ ]:
customer_df, order = csv_dowloader(csv_files= csv_files,
                                   source=URL,
                                   destination=DESTINATION,
                                   type='parquet')

trying to read: customers
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema
destination: ../data/public
customers shape: (2000, 5)
appending to the list:
../data/public/customers.parquet
==========
trying to read: orders
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema
destination: ../data/public
orders shape: (200, 5)
appending to the list:
../data/public/orders.parquet
==========

In [49]:

orders_df.head()

   order_id                  order_date  year  quarter     month
0         1  2020-04-14 19:59:10.340663  2020        2     April
1         2  2022-06-19 19:49:00.777498  2022        2      June
2         3  2023-04-22 10:34:29.264475  2023        2     April
3         4  2020-06-05 17:30:50.324055  2020        2      June
4         5  2022-11-08 07:38:02.311339  2022        4  November

In [50]:
customer_df.head()

,customer_id,customer_name,address,city,zip_code
0,1,Emily White,14752 Jones Ways,South Sean,59444
1,2,Chad Mcclain,7292 Anthony Lodge,Priceland,37902
2,3,Peter Holmes,682 Cook Corner Suite 430,Gayfurt,77812
3,4,Kathryn Cunningham,58670 Trujillo Ports,Tylerland,27254
4,5,Catherine Johnson,4617 Gray Cape,Reginaldhaven,66469

### With Pandas

In [3]:
def score_label(score):
    if score >= 90:
        return "Excellent"
    elif score >= 70:
        return "Good"
    elif score >= 50:
        return "Pass"
    else:
        return "Fail"

score_label(85)

'Good'

#### List Comprehension

In [12]:
import pandas as pd

df_scores = pd.DataFrame({
    "student": ["Anna", "Ben", "Chris", "Diana", "Eva"],
    "score": [95, 78, 61, 43, 88]
})

df_scores

  student  score
0    Anna     95
1     Ben     78
2   Chris     61
3   Diana     43
4     Eva     88

In [13]:
df_scores['label_lc'] = [score_label(i) for i in df_scores['score']]
df_scores

  student  score   label_lc
0    Anna     95  Excellent
1     Ben     78       Good
2   Chris     61       Pass
3   Diana     43       Fail
4     Eva     88       Good

#### `Apply`

In [14]:
df_scores['label_apply'] = df_scores['score'].apply(score_label)
df_scores

  student  score   label_lc label_apply
0    Anna     95  Excellent   Excellent
1     Ben     78       Good        Good
2   Chris     61       Pass        Pass
3   Diana     43       Fail        Fail
4     Eva     88       Good        Good

In [16]:
df_products_dummy = pd.DataFrame({
    "product": ["Milk", "Bread", "Juice", "Cheese", "Steak", "Apples"],
    "price": [2.5, 1.8, 6.2, 12.0, 24.5, 4.2]
})

df_products_dummy

  product  price
0    Milk    2.5
1   Bread    1.8
2   Juice    6.2
3  Cheese   12.0
4   Steak   24.5
5  Apples    4.2

In [17]:

def classify_price(price:float, low:int=5, high:int=15):
    if price <= low:
        return "Low-range product"
    elif price <= high:
        return "Mid-range product"
    else:
        return "High-range product"

classify_price(9)

'Mid-range product'

In [18]:
df_products_dummy['classify_price'] = df_products_dummy['price'].apply(classify_price)

In [19]:
df_products_dummy

  product  price      classify_price
0    Milk    2.5   Low-range product
1   Bread    1.8   Low-range product
2   Juice    6.2   Mid-range product
3  Cheese   12.0   Mid-range product
4   Steak   24.5  High-range product
5  Apples    4.2   Low-range product

In [20]:
def income_band(income, low=30000, high=70000):
    if income < low:
        return "Low income"
    elif income < high:
        return "Middle income"
    else:
        return "High income"

In [21]:
df_customers_dummy = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [22, 35, 47, 63, 29],
    "income": [18000, 42000, 72000, 95000, 25000]
})

df_customers_dummy

  customer  age  income
0        A   22   18000
1        B   35   42000
2        C   47   72000
3        D   63   95000
4        E   29   25000

In [22]:

df_customers_dummy["income_group"] = df_customers_dummy["income"].apply(income_band)
df_customers_dummy

  customer  age  income   income_group
0        A   22   18000     Low income
1        B   35   42000  Middle income
2        C   47   72000    High income
3        D   63   95000    High income
4        E   29   25000     Low income

In [23]:

df_customers_dummy["income_group"] = (df_customers_dummy["income"]
                                      .apply(income_band,
                                                        low = 15000,
                                                        high = 50000))
df_customers_dummy

  customer  age  income   income_group
0        A   22   18000  Middle income
1        B   35   42000  Middle income
2        C   47   72000    High income
3        D   63   95000    High income
4        E   29   25000  Middle income

In [25]:
df_customers_dummy[['income','income_group']].groupby('income_group').mean()

                     income
income_group
High income    83500.000000
Middle income  28333.333333

In [ ]:
df_scores["pass_flag"] = (df_scores["score"]
                          .apply(lambda x: "Pass" if x >= 50 else "Fail"))

# X is the same as df_scores["score"]

In [35]:
df_scores['test'] = df_scores['age']+df_scores['score']
df_scores

  student  score   label_lc label_apply pass_flag  age  newnumber  test
0    Anna     95  Excellent   Excellent      Pass   22        105   117
1     Ben     78       Good        Good      Pass   35         88   113
2   Chris     61       Pass        Pass      Pass   47         71   108
3   Diana     43       Fail        Fail      Fail   63         53   106
4     Eva     88       Good        Good      Pass   29         98   117