# Dates

## `Datetime`

In [2]:
from datetime import datetime, date, timedelta

In [3]:
simple_date = date(2024, 7, 1)
simple_date

datetime.date(2024, 7, 1)

In [16]:
simple_date = date(year = 2025, day = 20, month = 10 )

simple_date

datetime.date(2025, 10, 20)

In [19]:
simple_date.day
simple_date.year
simple_date.month

10

In [20]:
if simple_date.day>15:
    print('Ամիսը Կիսվավ')
else:
    print("Ամիսը նոր ա սկսվել")

Ամիսը Կիսվավ

In [5]:
if date.today().day>15:
    print('Ամիսը Կիսվավ')
else:
    print("Ամիսը նոր ա սկսվել")

Ամիսը նոր ա սկսվել

In [ ]:
"""
SQL
- campaign_id incremental
- campaign_name 
- campaign_descrpiton
- start_date
- end_date
"""

def create_campaign():
    # TODO: 
    pass


campaign_day = date.today()

In [9]:
datetime.now()

datetime.datetime(2026, 5, 10, 11, 42, 13, 147504)

In [12]:
dt = datetime(2025,5,10,12,10)

In [ ]:
print(f"Year: {dt.year}")
print(f"Month: {dt.month}")
print(f"Day: {dt.day}")
print(f"Hour: {dt.hour}")
print(f"Minute: {dt.minute}")
print(f"Second: {dt.second}")

Year: 2025
Month: 5
Day: 10
Hour: 12
Minute: 10
Second: 0

In [26]:
dt.strftime("%b/%y/%d/%H")

'May/25/10/12'

In [ ]:
mydate = "2024-07-01"
type(mydate)

str

In [ ]:
import pandas as pd
pd.read_csv( )

In [28]:
dt = datetime.strptime("2024-07-01", "%Y-%d-%m")
dt

datetime.datetime(2024, 1, 7, 0, 0)

In [31]:
start = date(2024, 7, 1)
end = date(2024, 7, 15)

delta = end - start
type(delta)

datetime.timedelta

In [32]:
print(type(delta.days))
delta.days

<class 'int'>

14

In [ ]:
def my_timedelta(years:int = 0, month:int = 0):
    my_date = timedelta(days=365 * years)+timedelta(days= 30*month)
    return my_date

In [ ]:
years = 2

start + timedelta(days=365 * years)

datetime.date(2026, 7, 1)

In [62]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates.to_csv('test.csv',index=False)

In [ ]:
df_dates = pd.read_csv('test.csv',
                       parse_dates=['signup_date','last_purchase'])
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [40]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      str
 2   last_purchase  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 352.0 bytes

In [ ]:
df_dates['new_signup_date'] = [datetime.strptime(i,"%Y-%m-%d") for i in df_dates['signup_date']]

In [43]:
df_dates['new_day'] = [i + timedelta(days=1) for i in df_dates['new_signup_date']]
df_dates

   customer_id signup_date last_purchase new_signup_date    new_day
0          101  2024-01-15    2024-06-01      2024-01-15 2024-01-16
1          102  2024-02-20    2024-06-15      2024-02-20 2024-02-21
2          103  2024-03-05    2024-07-01      2024-03-05 2024-03-06
3          104  2024-03-18    2024-07-08      2024-03-18 2024-03-19
4          105  2024-04-10    2024-07-12      2024-04-10 2024-04-11

In [51]:
df_dates['signup_date'] = pd.to_datetime(df_dates['signup_date'])

In [ ]:
df_dates.drop(columns=df_dates[['new_signup_date_1']],inplace=True)

   customer_id signup_date last_purchase new_signup_date    new_day
0          101  2024-01-15    2024-06-01      2024-01-15 2024-01-16
1          102  2024-02-20    2024-06-15      2024-02-20 2024-02-21
2          103  2024-03-05    2024-07-01      2024-03-05 2024-03-06
3          104  2024-03-18    2024-07-08      2024-03-18 2024-03-19
4          105  2024-04-10    2024-07-12      2024-04-10 2024-04-11

In [72]:
(df_dates["signup_date"].dt.dayofweek >= 5).astype(int)

0    0
1    0
2    0
3    0
4    0
Name: signup_date, dtype: int64

In [ ]:
df_dates["is_weekend"] = (df_dates["signup_date"].dt.dayofweek >= 5).astype(int)
df_dates[["signup_date", "signup_dow", "is_weekend"]]

In [70]:
df_dates['signup_date_don'] = df_dates['signup_date'].dt.day_name()
df_dates['signup_date_dow'] = df_dates['signup_date'].dt.day_of_week
df_dates['signup_date_dm'] = df_dates['signup_date'].dt.daysinmonth

df_dates

,customer_id,signup_date,last_purchase,signup_date_don,signup_date_dow,signup_date_dm
0,101,2024-01-15,2024-06-01,Monday,0,31
1,102,2024-02-20,2024-06-15,Tuesday,1,29
2,103,2024-03-05,2024-07-01,Tuesday,1,31
3,104,2024-03-18,2024-07-08,Monday,0,31
4,105,2024-04-10,2024-07-12,Wednesday,2,30

In [79]:
pd.concat([df_dates, pd.get_dummies(df_dates['signup_date_don'],drop_first=True)], axis=1)

,customer_id,signup_date,last_purchase,signup_date_don,signup_date_dow,signup_date_dm,Tuesday,Wednesday
0,101,2024-01-15,2024-06-01,Monday,0,31,False,False
1,102,2024-02-20,2024-06-15,Tuesday,1,29,True,False
2,103,2024-03-05,2024-07-01,Tuesday,1,31,True,False
3,104,2024-03-18,2024-07-08,Monday,0,31,False,False
4,105,2024-04-10,2024-07-12,Wednesday,2,30,False,True

In [57]:
df_dates['last_purchase'] = pd.to_datetime(df_dates['last_purchase'])

In [61]:
df_dates['last_purchase_dow']= df_dates['last_purchase'].dt.day_of_week
df_dates

df_dates['last_purchase_doy']= df_dates['last_purchase'].dt.day_of_year
df_dates

,customer_id,signup_date,last_purchase,new_signup_date,new_day,last_purchase_dow,last_purchase_dow1,last_purchase_doy
0,101,2024-01-15,2024-06-01,2024-01-15,2024-01-16,5,5,153
1,102,2024-02-20,2024-06-15,2024-02-20,2024-02-21,5,5,167
2,103,2024-03-05,2024-07-01,2024-03-05,2024-03-06,0,0,183
3,104,2024-03-18,2024-07-08,2024-03-18,2024-03-19,0,0,190
4,105,2024-04-10,2024-07-12,2024-04-10,2024-04-11,4,4,194

In [ ]:
df_dates['signup_month_sm'] = df_dates['signup_date'].dt.to_period("M").dt.start_time
df_dates['signup_month_em'] = df_dates['signup_date'].dt.to_period("M").dt.
df_dates

,customer_id,signup_date,last_purchase,signup_date_don,signup_date_dow,signup_date_dm,signup_month,signup_month_sm,signup_month_em
0,101,2024-01-15,2024-06-01,Monday,0,31,2024-01-01,2024-01-01,2024-01-31 23:59:59.999999
1,102,2024-02-20,2024-06-15,Tuesday,1,29,2024-02-01,2024-02-01,2024-02-29 23:59:59.999999
2,103,2024-03-05,2024-07-01,Tuesday,1,31,2024-03-01,2024-03-01,2024-03-31 23:59:59.999999
3,104,2024-03-18,2024-07-08,Monday,0,31,2024-03-01,2024-03-01,2024-03-31 23:59:59.999999
4,105,2024-04-10,2024-07-12,Wednesday,2,30,2024-04-01,2024-04-01,2024-04-30 23:59:59.999999

In [81]:
df_dates.sort_values("signup_date",ascending=True)

,customer_id,signup_date,last_purchase,signup_date_don,signup_date_dow,signup_date_dm
0,101,2024-01-15,2024-06-01,Monday,0,31
1,102,2024-02-20,2024-06-15,Tuesday,1,29
2,103,2024-03-05,2024-07-01,Tuesday,1,31
3,104,2024-03-18,2024-07-08,Monday,0,31
4,105,2024-04-10,2024-07-12,Wednesday,2,30

In [82]:
for i in range(6):
    print(i)

0
1
2
3
4
5

In [93]:
pd.date_range(start="2024-07-01", periods=2, freq="ME")

DatetimeIndex(['2024-07-31', '2024-08-31'], dtype='datetime64[us]', freq='ME')