In [2]:

## Import Libraries

In [3]:
import os
import pandas as pd
import geopandas as gpd


from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry

In [4]:
## Defining File Paths

In [14]:
DATA_DIR = Path("../data/citibike")

citibike_path = DATA_DIR / "JC2025.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

In [6]:
## connection string

In [7]:
DB_USER = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "citibike"

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

In [8]:
engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

In [9]:
### Testing The connections

In [10]:

with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 17.0 (Debian 17.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

In [ ]:
### Testing The connections

In [8]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

In [9]:
## Loading the Citibike Data

### Defining Data Paths

>Adjust paths based on your course project structure.

In [16]:
DATA_DIR = Path("../data/citibike/JC")

citibike_path = DATA_DIR / "JC2025.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

In [17]:
### Reading Citi Bike CSV

In [18]:

citibike_df = pd.read_csv(citibike_path)

citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9F734BE1BFC45FF4,electric_bike,2025-11-18 18:34:14.943,2025-11-18 18:47:33.391,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member
1,B6C773B13AC0E465,classic_bike,2025-11-26 16:29:15.513,2025-11-26 16:43:45.235,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member
2,C300465AA158280F,electric_bike,2025-11-04 22:31:58.010,2025-11-04 22:38:57.017,Bloomfield St & 15 St,HB203,Marshall St & 2 St,HB408,40.754530,-74.026580,40.740802,-74.042521,member
3,31A424FC97C8AAFB,classic_bike,2025-11-08 06:51:57.424,2025-11-08 06:57:45.627,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member
4,08C5EA04CB1FDC57,classic_bike,2025-11-24 20:31:21.758,2025-11-24 20:38:01.261,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member

In [15]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

In [16]:
### Cleaning Data Types

In [18]:
citibike_df["started_at"] = pd.to_datetime(
    citibike_df["started_at"],
    errors="coerce"
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df["ended_at"],
    errors="coerce"
)

In [ ]:
>Create a date column for easier joins with weather data.

In [19]:
citibike_df["ride_date"] = citibike_df["started_at"].dt.date

citibike_df["ride_date"] = pd.to_datetime(
    citibike_df["ride_date"],
    errors="coerce"
)

citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  9F734BE1BFC45FF4 2025-11-18 18:34:14.943 2025-11-18 18:47:33.391 2025-11-18
1  B6C773B13AC0E465 2025-11-26 16:29:15.513 2025-11-26 16:43:45.235 2025-11-26
2  C300465AA158280F 2025-11-04 22:31:58.010 2025-11-04 22:38:57.017 2025-11-04
3  31A424FC97C8AAFB 2025-11-08 06:51:57.424 2025-11-08 06:57:45.627 2025-11-08
4  08C5EA04CB1FDC57 2025-11-24 20:31:21.758 2025-11-24 20:38:01.261 2025-11-24

In [20]:
## Writing Citi Bike Data to PostGIS Database

>Although the database has PostGIS, this first table is still normal tabular data.

SyntaxError: invalid syntax (1832010207.py, line 3)

In [21]:
citibike_df.to_sql(
    name="jersey_city",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=50_000,
    method="multi"
)

1002704

In [22]:
## Loading Weather Data

In [22]:
weather_df = pd.read_csv(weather_path)


weather_df.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,10.9,3.9,7.4,4.5,4.5,0.0,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.0,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.0,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1
4,2025-01-05,0.3,-3.6,-2.2,0.0,0.0,0.0,19.9

In [23]:
weather_df["date"] = pd.to_datetime(
    weather_df["date"],
    errors="coerce"
)

weather_df.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,10.9,3.9,7.4,4.5,4.5,0.0,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.0,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.0,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1
4,2025-01-05,0.3,-3.6,-2.2,0.0,0.0,0.0,19.9

In [24]:
weather_df.to_sql(
    name="jersey_weather",
    con=engine,
    if_exists="replace",
    index=False
)

365

In [27]:

neighborhood_gdf = gpd.read_file(neighborhood_path)

neighborhood_gdf.head()

neighborhood_gdf.crs





neighborhood_gdf = neighborhood_gdf.to_crs("EPSG:4326")





neighborhood_gdf.geom_type.value_counts()

Polygon    53
Name: count, dtype: int64

In [28]:
neighborhood_gdf.to_postgis(
    name="jersey_city_neighborhoods",
    con=engine,
    if_exists="replace",
    index=False
)

In [29]:
query = """
SELECT
    neighborhood,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jersey_city_neighborhoods
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

     neighborhood geometry_type  srid
0    Port Liberte    ST_Polygon  4326
1  LSP Industrial    ST_Polygon  4326
2      Hackensack    ST_Polygon  4326
3       Lafayette    ST_Polygon  4326
4    Jackson Hill    ST_Polygon  4326

In [30]:
start_stations = citibike_df[
    [
        "ride_id",
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lng"
    ]
].copy()

start_stations = start_stations.rename(
    columns={
        "start_station_id": "station_id",
        "start_station_name": "station_name",
        "start_lat": "lat",
        "start_lng": "lng"
    }
)

start_stations["activity_type"] = "departure"

In [31]:

end_stations = citibike_df[
    [
        "ride_id",
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lng"
    ]
].copy()

end_stations = end_stations.rename(
    columns={
        "end_station_id": "station_id",
        "end_station_name": "station_name",
        "end_lat": "lat",
        "end_lng": "lng"
    }
)

end_stations["activity_type"] = "arrival"

In [32]:


station_activity_long = pd.concat(
    [
        start_stations,
        end_stations
    ],
    ignore_index=True
)

station_activity_long = station_activity_long.dropna(
    subset=[
        "station_id",
        "station_name",
        "lat",
        "lng"
    ]
)

In [33]:

station_activity_agg = (
    station_activity_long
    .groupby(
        [
            "station_id",
            "station_name",
            "lat",
            "lng",
            "activity_type"
        ],
        as_index=False
    )
    .agg(
        number_of_rides=("ride_id", "count")
    )
)

In [34]:

station_summary = (
    station_activity_agg
    .pivot_table(
        index=[
            "station_id",
            "station_name",
            "lat",
            "lng"
        ],
        columns="activity_type",
        values="number_of_rides",
        fill_value=0
    )
    .reset_index()
)

station_summary.columns.name = None

station_summary = station_summary.rename(
    columns={
        "departure": "total_departures",
        "arrival": "total_arrivals"
    }
)

if "total_departures" not in station_summary.columns:
    station_summary["total_departures"] = 0

if "total_arrivals" not in station_summary.columns:
    station_summary["total_arrivals"] = 0

station_summary["total_activity"] = (
    station_summary["total_departures"] +
    station_summary["total_arrivals"]
)

station_summary["net_departures"] = (
    station_summary["total_departures"] -
    station_summary["total_arrivals"]
)

station_summary = station_summary.sort_values(
    "total_activity",
    ascending=False
).reset_index(drop=True)

station_summary.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures
0,JC115,Grove St PATH,40.719410,-74.043090,47744.0,45121.0,92865.0,-2623.0
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,26638.0,25964.0,52602.0,-674.0
2,JC009,Hamilton Park,40.727596,-74.044247,22347.0,22311.0,44658.0,-36.0
3,HB106,River St & Newark St,40.736722,-74.029007,22113.0,21489.0,43602.0,-624.0
4,JC066,Newport PATH,40.727224,-74.033759,20698.0,20704.0,41402.0,6.0

In [35]:
station_gdf = gpd.GeoDataFrame(
    station_summary,
    geometry=gpd.points_from_xy(
        station_summary["lng"],
        station_summary["lat"]
    ),
    crs="EPSG:4326"
)

station_gdf.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures,geometry
0,JC115,Grove St PATH,40.719410,-74.043090,47744.0,45121.0,92865.0,-2623.0,POINT (-74.04309 40.71941)
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,26638.0,25964.0,52602.0,-674.0,POINT (-74.0303 40.73594)
2,JC009,Hamilton Park,40.727596,-74.044247,22347.0,22311.0,44658.0,-36.0,POINT (-74.04425 40.7276)
3,HB106,River St & Newark St,40.736722,-74.029007,22113.0,21489.0,43602.0,-624.0,POINT (-74.02901 40.73672)
4,JC066,Newport PATH,40.727224,-74.033759,20698.0,20704.0,41402.0,6.0,POINT (-74.03376 40.72722)

In [36]:
station_gdf.to_postgis(
    name="jc_stations",
    con=engine,
    if_exists="replace",
    index=False
)

In [37]:

query = """
SELECT
    station_id,
    station_name,
    total_activity,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jc_stations
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,station_id,station_name,total_activity,geometry_type,srid
0,JC115,Grove St PATH,92865.0,ST_Point,4326
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,52602.0,ST_Point,4326
2,JC009,Hamilton Park,44658.0,ST_Point,4326
3,HB106,River St & Newark St,43602.0,ST_Point,4326
4,JC066,Newport PATH,41402.0,ST_Point,4326

In [38]:
## SQL Alchemy

In [39]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

pd.read_sql(
    query,
    con=engine
)

                  table_name
0          geography_columns
1           geometry_columns
2                jc_stations
3                jersey_city
4  jersey_city_neighborhoods
5             jersey_weather
6            spatial_ref_sys

In [ ]:
query = """
SELECT
    started_at::date AS ride_date,
    COUNT(*) AS number_of_rides
FROM jersey_city
GROUP BY started_at::date
ORDER BY ride_date;
"""

daily_rides_sql = pd.read_sql(
    query,
    con=engine
)

daily_rides_sql.head()

DatabaseError: Execution failed on sql '
SELECT
    started_at::date AS ride_date,
    COUNT(*) AS number_of_rides
FROM jc_2025
GROUP BY started_at::date
ORDER BY ride_date;
': (psycopg2.errors.UndefinedTable) relation "jc_2025" does not exist
LINE 5: FROM jc_2025
             ^

[SQL:
SELECT
    started_at::date AS ride_date,
    COUNT(*) AS number_of_rides
FROM jc_2025
GROUP BY started_at::date
ORDER BY ride_date;
]
(Background on this error at: https://sqlalche.me/e/20/f405)