In [2]:

## Import Libraries

In [ ]:
import os
import pandas as pd
import geopandas as gpd


from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry

In [3]:
## Defining File Paths

In [4]:
DATA_DIR = Path("../data/citibike")

citibike_path = DATA_DIR / "JC2025.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

In [ ]:
## connection string

In [5]:
DB_USER = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "citibike"

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

In [6]:
engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

In [ ]:
### Testing The connections

In [7]:

with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 17.0 (Debian 17.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

In [ ]:
### Test PostGIS Extension

In [8]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

In [9]:
## Loading the Citibike Data

### Defining Data Paths

>Adjust paths based on your course project structure.

In [13]:
DATA_DIR = Path("../data/citibike/JC")

citibike_path = DATA_DIR / "JC2025.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

In [ ]:
### Reading Citi Bike CSV

In [14]:

citibike_df = pd.read_csv(citibike_path)

citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9F734BE1BFC45FF4,electric_bike,2025-11-18 18:34:14.943,2025-11-18 18:47:33.391,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member
1,B6C773B13AC0E465,classic_bike,2025-11-26 16:29:15.513,2025-11-26 16:43:45.235,Glenwood Ave,JC094,West Side Ave & Stegman Pkwy,JC131,40.727551,-74.071061,40.710870,-74.093680,member
2,C300465AA158280F,electric_bike,2025-11-04 22:31:58.010,2025-11-04 22:38:57.017,Bloomfield St & 15 St,HB203,Marshall St & 2 St,HB408,40.754530,-74.026580,40.740802,-74.042521,member
3,31A424FC97C8AAFB,classic_bike,2025-11-08 06:51:57.424,2025-11-08 06:57:45.627,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member
4,08C5EA04CB1FDC57,classic_bike,2025-11-24 20:31:21.758,2025-11-24 20:38:01.261,Clinton St & 7 St,HB303,Marshall St & 2 St,HB408,40.745420,-74.033320,40.740802,-74.042521,member

In [15]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

In [16]:
### Cleaning Data Types

In [18]:
citibike_df["started_at"] = pd.to_datetime(
    citibike_df["started_at"],
    errors="coerce"
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df["ended_at"],
    errors="coerce"
)

In [ ]:
>Create a date column for easier joins with weather data.

In [19]:
citibike_df["ride_date"] = citibike_df["started_at"].dt.date

citibike_df["ride_date"] = pd.to_datetime(
    citibike_df["ride_date"],
    errors="coerce"
)

citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  9F734BE1BFC45FF4 2025-11-18 18:34:14.943 2025-11-18 18:47:33.391 2025-11-18
1  B6C773B13AC0E465 2025-11-26 16:29:15.513 2025-11-26 16:43:45.235 2025-11-26
2  C300465AA158280F 2025-11-04 22:31:58.010 2025-11-04 22:38:57.017 2025-11-04
3  31A424FC97C8AAFB 2025-11-08 06:51:57.424 2025-11-08 06:57:45.627 2025-11-08
4  08C5EA04CB1FDC57 2025-11-24 20:31:21.758 2025-11-24 20:38:01.261 2025-11-24

In [20]:
## Writing Citi Bike Data to PostGIS Database

>Although the database has PostGIS, this first table is still normal tabular data.

SyntaxError: invalid syntax (1832010207.py, line 3)

In [21]:
citibike_df.to_sql(
    name="jersey_city",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=50_000,
    method="multi"
)

1002704

In [22]:
## Loading Weather Data

In [23]:
weather_df = pd.read_csv(weather_path)

weather_df.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,10.9,3.9,7.4,4.5,4.5,0.0,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.0,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.0,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1
4,2025-01-05,0.3,-3.6,-2.2,0.0,0.0,0.0,19.9

In [24]:
weather_df["date"] = pd.to_datetime(
    weather_df["date"],
    errors="coerce"
)

weather_df.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,10.9,3.9,7.4,4.5,4.5,0.0,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.0,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.0,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1
4,2025-01-05,0.3,-3.6,-2.2,0.0,0.0,0.0,19.9

In [25]:
weather_df.to_sql(
    name="jersey_weather",
    con=engine,
    if_exists="replace",
    index=False
)

365

In [ ]:
# Load Neighborhood GeoJSON as Spatial Table

## Read GeoJSON with GeoPandas

```{python}
#| echo: true

neighborhood_gdf = gpd.read_file(neighborhood_path)

neighborhood_gdf.head()
```

---

## Check CRS

```{python}
#| echo: true

neighborhood_gdf.crs
```

The file should be in:

```text
EPSG:4326
```

If not, convert it.

```{python}
#| echo: true

neighborhood_gdf = neighborhood_gdf.to_crs("EPSG:4326")
```

---

## Inspect Geometry Type

```{python}
#| echo: true

neighborhood_gdf.geom_type.value_counts()
```

For neighborhoods, we expect:

```text
Polygon
```

or:

```text
MultiPolygon
```

---

## Write GeoDataFrame to PostGIS

Because this is a spatial table, we use `GeoDataFrame.to_postgis()`.

```{python}
#| echo: true

neighborhood_gdf.to_postgis(
    name="jersey_city_neighborhoods",
    con=engine,
    if_exists="replace",
    index=False
)
```

This creates a real geometry column in PostgreSQL.