In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)


months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [ ]:
from utils_ploty import *

In [25]:
px.defaults.template = "plotly_white"

## Bar Plot `Sales by Region`

[Execution order](https://hovhannisyan91.github.io/aca/materials/sql/slides/session03.html#/execution-order)

In [10]:
region_sales = df_plotly.groupby('region', as_index=False)['sales'].sum()
region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [21]:
fig = px.bar(
    data_frame  = region_sales,
    x = 'region',
    y = 'sales',
    title = "Total Sales by Region",
    text = 'sales'   
)

fig.update_traces(
    textposition = 'outside'
)

fig.update_layout(
    xaxis_title = '',
    yaxis_title = 'Sales'
)
fig.show()

## Simple Line Chart

In [23]:
monthly_sales = df_plotly.groupby("month",as_index=False)['sales'].sum()
monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [29]:
fig  = px.line(
    data_frame = monthly_sales,
    x = 'month',
    y = 'sales',
    markers = True,
    title = 'Monthly Sales' 

)

fig.update_layout(
    xaxis_title = 'Month',
    yaxis_title = 'Total Sales'
)

fig.show()


## Histogram

In [37]:
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [ ]:
MY_VAR = 'units'
X_TITLE = 'Units'
# for i in list 
fig = px.histogram(
    data_frame = df_plotly,
    x = MY_VAR,
    nbins = 15,
    title = 'Sales Distribution'
)

fig.update_layout(
    xaxis_title = X_TITLE,
    yaxis_title = 'Frequency'
)
fig.show()

## Example 4

In [43]:
fig  = px.scatter(
    data_frame = df_plotly,
    x = 'customers',
    y = 'sales',
    color =  'region',
    size = 'units',
    hover_data = ["product", 'units'],
    title = 'Customers vs Sales'
)


# fig.update_layout(
#     # add x and y axis titles
# )
fig.show()

In [ ]:
## color in Line Chart

In [46]:
monthly_sales_region = (df_plotly
                        .groupby(['region','month'],as_index=False)['sales'].sum()
                        )

monthly_sales_region.head()

  region      month  sales
0   East 2024-01-01    217
1   East 2024-02-01    273
2   East 2024-03-01    250
3   East 2024-04-01    216
4   East 2024-05-01    350

In [52]:
fig = px.line(
    data_frame = monthly_sales_region,
    x = 'month',
    y = 'sales',
    color = 'region',
    markers = True
)

fig.update_layout(
    # x
    # y
    legend_title  = 'Region'
)

fig.show()

In [53]:
region_product_sales = (df_plotly
                        .groupby(['region','product'],as_index=False)['sales'].sum()
                        )

region_product_sales.head()

  region product  sales
0   East       A    853
1   East       B    706
2  North       A    888
3  North       B    912
4  South       A    958

In [65]:
fig  = px.bar(
    data_frame = region_product_sales,
    x = 'region',
    y = 'sales',
    color = 'product',
    orientation = 'v',
    barmode = 'group' 

)

fig.update_layout(
    # x
    # y
    legend_title  = 'Product'
)

In [66]:
fig  = px.bar(
    data_frame = region_product_sales,
    y = 'region',
    x = 'sales',
    color = 'product',
    orientation = 'h',
    barmode = 'group' 

)

fig.update_layout(
    # x
    # y
    legend_title  = 'Product'
)

## Donut Chart

In [68]:
product_sales = df_plotly.groupby('product', as_index= False)['sales'].sum()
product_sales

  product  sales
0       A   2699
1       B   2334

In [71]:
fig = px.pie(
    data_frame = product_sales,
    names = 'product',
    values = 'sales',
    hole = 0.5
)

fig.show()

In [ ]:
## Color

In [77]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    
    color_discrete_sequence=["#aa4726"]
)

fig.show()

In [79]:
fig  = px.bar(
    data_frame = region_product_sales,
    y = 'region',
    x = 'sales',
    color = 'product',
    orientation = 'h',
    barmode = 'group',
    color_discrete_sequence=["#3B6EAD", "#AFC4E8"]

)

fig.update_layout(
    # x
    # y
    legend_title  = 'Product'
)

In [83]:
fig  = px.bar(
    data_frame = region_product_sales,
    x = 'region',
    y = 'sales',
    color = 'product',
    orientation = 'v',
    barmode = 'group',
    # color_discrete_sequence=["#3B6EAD", "#AFC4E8"]
    color_discrete_map = {
        'A':'red',
        'B': 'blue'
    }

)

fig.update_layout(
    # x
    # y
    legend_title  = 'Product'
)

In [84]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales",
    color_discrete_sequence=["crimson"]
)

fig.show()

## Highlights

In [90]:
region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [88]:
max_index = region_sales['sales'].idxmax()
max_index

1

In [89]:


top_region = region_sales.loc[max_index,'region']
top_region

'North'

In [92]:
region_sales['highlight'] = np.where(
        region_sales['region'] == top_region, 'Top Region', 'Other Regions'
        )

region_sales

  region  sales      highlight
0   East   1559  Other Regions
1  North   1800     Top Region
2  South   1674  Other Regions

In [ ]:


fig.update_traces(textposition="outside")

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

In [101]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    color = 'highlight',
    title="Total Sales by Region",
    color_discrete_map={
        'Top Region': "#3B6EAD",
        'Other Regions': "#D9D9D9"
    },
    text= 'sales'
)

fig.update_traces(
    textposition = 'inside'
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

In [104]:
region_sales

  region  sales      highlight
0   East   1559  Other Regions
1  North   1800     Top Region
2  South   1674  Other Regions

In [110]:
fig = px.pie(
    data_frame = region_sales,
    names = 'highlight',
    color = 'highlight',
    values = 'sales',
    hole = 0.5,
    color_discrete_map={
        'Top Region': "#3B6EAD",
        'Other Regions': "#D9D9D9"
    }
)



fig.show()

In [112]:
region_sales

  region  sales      highlight
0   East   1559  Other Regions
1  North   1800     Top Region
2  South   1674  Other Regions

## Line Chart highlight

In [118]:
monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [129]:
min_sales_idx = monthly_sales['sales'].idxmin()

min_monthly_sales = monthly_sales.loc[min_sales_idx]
x_min = min_monthly_sales[['month']]
y_min = min_monthly_sales[['sales']]

In [130]:
max_sales_idx = monthly_sales['sales'].idxmax()

max_monthly_sales = monthly_sales.loc[max_sales_idx]
x_max = max_monthly_sales[['month']]
y_max = max_monthly_sales[['sales']]

In [ ]:
monthly_sales_region

In [ ]:
fig = px.line(
    data_frame = monthly_sales,
    x = 'month',
    y = 'sales'
    # color = 'region',
    # markers = True
)

fig.add_scatter(x = x_max, 
                y = y_max,
                mode = 'markers',
                name = 'Maximum',
                marker=dict(size=14, color="#ABEAA5"),
                )

fig.add_scatter(x = x_min, 
                y = y_min,
                mode = 'markers',
                name = 'Minimum',
                marker=dict(size=14, color="#B22E24"),
                )

fig.update_layout(
    # x
    # y
    # legend_title  = 'Region'
)

fig.show()

In [145]:
df_hist = df_plotly.copy()

df_hist["highlight"] = np.where(
    df_hist["region"] == top_region,
    "Highest Sales Region",
    "Other Regions"
)

df_hist.head()

,month,region,product,sales,customers,units,month_name,highlight
0,2024-01-01,North,A,182,71,38,Jan,Highest Sales Region
1,2024-01-01,North,B,94,80,30,Jan,Highest Sales Region
2,2024-01-01,South,A,182,43,12,Jan,Other Regions
3,2024-01-01,South,B,132,21,33,Jan,Other Regions
4,2024-01-01,East,A,117,21,69,Jan,Other Regions

In [148]:
fig = px.histogram(
    df_hist,
    x="sales",
    color="highlight",
    barmode="overlay",
    opacity=0.5,
    title="Distribution with Highlighted Largest Category",
    color_discrete_map={
        "Highest Sales Region": "#3B6EAD",
        "Other Regions": "#D9D9D9"
    }
)

fig.update_layout(
    xaxis_title="Sales",
    yaxis_title="Count",
    legend_title=""
)

fig.show()

In [151]:
avg_sales = monthly_sales['sales'].mean()
avg_sales

np.float64(838.8333333333334)

In [157]:
fig = px.line(
    data_frame = monthly_sales,
    x = 'month',
    y = 'sales'
    # color = 'region',
    # markers = True
)

fig.add_scatter(x = x_max, 
                y = y_max,
                mode = 'markers',
                name = 'Maximum',
                marker=dict(size=14, color="#ABEAA5"),
                )

fig.add_scatter(x = x_min, 
                y = y_min,
                mode = 'markers',
                name = 'Minimum',
                marker=dict(size=14, color="#B22E24"),
                )

fig.add_hline(
            y = avg_sales,
            line_dash = 'dash',
            annotation_text  = 'Average Sales',
            annotation_position  = 'top left',
              )
fig.update_layout(
    # x
    # y
    # legend_title  = 'Region'
)

fig.show()

In [158]:
campaign_start = pd.Timestamp("2024-04-01")

In [181]:
fig = px.line(
    data_frame = monthly_sales,
    x = 'month',
    y = 'sales',

    # color = 'region',
    # markers = True
)

fig.update_yaxes(
    rangemode="tozero"
)

# fig.add_scatter(x = x_max, 
#                 y = y_max,
#                 mode = 'markers',
#                 name = 'Maximum',
#                 marker=dict(size=14, color="#ABEAA5"),
#                 )

# fig.add_scatter(x = x_min, 
#                 y = y_min,
#                 mode = 'markers',
#                 name = 'Minimum',
#                 marker=dict(size=14, color="#B22E24"),
#                 )

# # fig.add_hline(
# #             y = avg_sales,
# #             line_dash = 'dash',
# #             annotation_text  = 'Average Sales',
# #             annotation_position  = 'bottom left',
# #               )

# fig.add_vline(
#     x = campaign_start,
#     line_dash = 'dot',
#     line_color = 'red'

# )


# fig.add_annotation(
#     x=campaign_start,
#     y=monthly_sales["sales"].max(),
#     text="Campaign Start",
#     showarrow=True,
#     arrowhead=2,
#     ax=40,
#     ay=-40
# )
# fig.update_layout(
#     # x
#     # y
#     # legend_title  = 'Region'
# )

fig.show()